SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS A INNER JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_OUTCOME NOT LIKE "Intact%"
AND B.SEX_UPON_INTAKE LIKE "Intact%"
ORDER BY A.ANIMAL_ID;